
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Aug 20 11:52:44 EDT 2004
//----------------------------------------------------

package jasmin;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 45;
  public static final int TABLESWITCH = 42;
  public static final int DTHROWS = 13;
  public static final int DCATCH = 2;
  public static final int STRICTFP = 40;
  public static final int USING = 25;
  public static final int PRIVATE = 33;
  public static final int DSOURCE = 12;
  public static final int INTERFACE = 31;
  public static final int STATIC = 36;
  public static final int LOOKUPSWITCH = 41;
  public static final int DCODE_ATTR = 17;
  public static final int IS = 26;
  public static final int DINTERFACE = 16;
  public static final int Str = 47;
  public static final int DSYNTHETIC = 23;
  public static final int DFIELD = 5;
  public static final int Int = 50;
  public static final int DCLASS = 3;
  public static final int ABSTRACT = 29;
  public static final int EOF = 0;
  public static final int DINNER_CLASS_ATTR = 21;
  public static final int METHOD = 28;
  public static final int TRANSIENT = 38;
  public static final int error = 1;
  public static final int Insn = 49;
  public static final int Word = 48;
  public static final int DSUPER = 10;
  public static final int DLIMIT = 6;
  public static final int EQ = 44;
  public static final int Num = 51;
  public static final int DIMPLEMENTS = 15;
  public static final int FROM = 27;
  public static final int DMETHOD = 8;
  public static final int COLON = 46;
  public static final int DFIELD_ATTR = 19;
  public static final int NATIVE = 32;
  public static final int PROTECTED = 34;
  public static final int TO = 24;
  public static final int DEND = 4;
  public static final int FINAL = 30;
  public static final int DINNER_CLASS_SPEC_ATTR = 22;
  public static final int DEFAULT = 43;
  public static final int PUBLIC = 35;
  public static final int DCLASS_ATTR = 18;
  public static final int DNOSUPER = 11;
  public static final int VOLATILE = 39;
  public static final int DVAR = 14;
  public static final int SYNCHRONIZED = 37;
  public static final int DSET = 9;
  public static final int DLINE = 7;
  public static final int DMETHOD_ATTR = 20;
}

