
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Jul 06 09:41:18 EDT 2004
//----------------------------------------------------

package jasmin;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 42;
  public static final int TABLESWITCH = 39;
  public static final int DTHROWS = 13;
  public static final int DCATCH = 2;
  public static final int STRICTFP = 37;
  public static final int USING = 22;
  public static final int PRIVATE = 30;
  public static final int DSOURCE = 12;
  public static final int INTERFACE = 28;
  public static final int STATIC = 33;
  public static final int LOOKUPSWITCH = 38;
  public static final int DCODE_ATTR = 17;
  public static final int IS = 23;
  public static final int DINTERFACE = 16;
  public static final int Str = 44;
  public static final int DFIELD = 5;
  public static final int Int = 47;
  public static final int DCLASS = 3;
  public static final int ABSTRACT = 26;
  public static final int EOF = 0;
  public static final int METHOD = 25;
  public static final int TRANSIENT = 35;
  public static final int error = 1;
  public static final int Insn = 46;
  public static final int Word = 45;
  public static final int DSUPER = 10;
  public static final int DLIMIT = 6;
  public static final int EQ = 41;
  public static final int Num = 48;
  public static final int DIMPLEMENTS = 15;
  public static final int FROM = 24;
  public static final int DMETHOD = 8;
  public static final int COLON = 43;
  public static final int DFIELD_ATTR = 19;
  public static final int NATIVE = 29;
  public static final int PROTECTED = 31;
  public static final int TO = 21;
  public static final int DEND = 4;
  public static final int FINAL = 27;
  public static final int DEFAULT = 40;
  public static final int PUBLIC = 32;
  public static final int DCLASS_ATTR = 18;
  public static final int DNOSUPER = 11;
  public static final int VOLATILE = 36;
  public static final int DVAR = 14;
  public static final int SYNCHRONIZED = 34;
  public static final int DSET = 9;
  public static final int DLINE = 7;
  public static final int DMETHOD_ATTR = 20;
}

